load("@rules_java//java:defs.bzl", "java_test")

java_test(
  name = "AccountantMergerTest",
  srcs = ["AccountantMergerTest.java"],
  test_class = "eflect.data.AccountantMergerTest",
  deps = [
    "//java/eflect/data",
    "//java/eflect/testing/data",
  ],
)

java_test(
  name = "EnergyAccountantTest",
  srcs = ["EnergyAccountantTest.java"],
  test_class = "eflect.data.EnergyAccountantTest",
  deps = [
    "//java/eflect/data",
    "//java/eflect/testing/data",
  ],
)

java_test(
  name = "StackTraceAlignerTest",
  srcs = ["StackTraceAlignerTest.java"],
  test_class = "eflect.data.StackTraceAlignerTest",
  deps = [
    "//java/eflect/data",
    "//java/eflect/testing/data",
  ],
)
