load("@rules_java//java:defs.bzl", "java_library")

java_library(
  name = "jiffies",
  visibility = ["//visibility:public"],
  srcs = [
    "JiffiesEnergyAccountant.java",
  ],
  deps = [
    "//java-core/eflect/data",
    "//java-core/eflect/data/jiffies",
    "//java-core/eflect/util",
    "@jRAPL//src/java/jrapl",
  ],
)
