load("@rules_java//java:defs.bzl", "java_test")

java_test(
  name = "JiffiesAccountantTest_NotEnoughData",
  srcs = ["JiffiesAccountantTest_NotEnoughData.java"],
  test_class = "eflect.data.jiffies.JiffiesAccountantTest_NotEnoughData",
  deps = [
    "//java/eflect/data",
    "//java/eflect/data/jiffies",
    "//java/eflect/testing/data/jiffies",
  ],
)

java_test(
  name = "JiffiesAccountantTest_AccountableData",
  srcs = ["JiffiesAccountantTest_AccountableData.java"],
  test_class = "eflect.data.jiffies.JiffiesAccountantTest_AccountableData",
  deps = [
    "//java/eflect/data",
    "//java/eflect/data/jiffies",
    "//java/eflect/testing/data/jiffies",
  ],
)
