load("@rules_java//java:defs.bzl", "java_test")

java_test(
  name = "JiffiesAccountantTest1",
  srcs = ["JiffiesAccountantTest1.java"],
  test_class = "eflect.data.jiffies.JiffiesAccountantTest1",
  deps = [
    "//java/eflect/data",
    "//java/eflect/data/jiffies",
    "//java/eflect/testing/data/jiffies",
  ],
)

java_test(
  name = "JiffiesAccountantTest2",
  srcs = ["JiffiesAccountantTest2.java"],
  test_class = "eflect.data.jiffies.JiffiesAccountantTest2",
  deps = [
    "//java/eflect/data",
    "//java/eflect/data/jiffies",
    "//java/eflect/testing/data/jiffies",
  ],
)
