load("@rules_java//java:defs.bzl", "java_library")

java_library(
  name = "utils",
  visibility = ["//visibility:public"],
  srcs = glob(["*.java"]),
  deps = [
    "@jRAPL//src/java/jrapl",
    "@net_java_dev_jna_jna//jar",
  ]
)
