load("@rules_java//java:defs.bzl", "java_library")

java_library(
  name = "jiffies",
  visibility = ["//visibility:public"],
  srcs = glob(["*.java"]),
  deps = [
    "//java-core/eflect/data",
  ],
)
