load("@rules_java//java:defs.bzl", "java_test")

java_test(
  name = "EflectTest",
  visibility = ["//visibility:public"],
  srcs = ["EflectTest.java"],
  deps = [
    "//java/eflect",
    "//protos/sample:sample_java_protos"
  ],
)
