load("@rules_java//java:defs.bzl", "java_test")

java_test(
  name = "SamplingFutureTest",
  visibility = ["//visibility:public"],
  srcs = ["SamplingFutureTest.java"],
  deps = [
    "//java/eflect/util",
  ],
)
