load("@rules_java//java:defs.bzl", "java_test")

java_test(
  name = "RangeMapTest",
  srcs = ["RangeMapTest.java"],
  test_class = "eflect.util.RangeMapTest",
  deps = [
    "//java/eflect/util",
  ],
)
