load("@rules_java//java:defs.bzl", "java_test")

java_test(
  name = "CollectingFutureTest",
  visibility = ["//visibility:public"],
  srcs = ["CollectingFutureTest.java"],
  deps = [
    "//java/eflect/util",
  ],
)
